import { StyleSheet } from 'react-native';
import { ThemeColors } from './theme';

export function createFormStyles(c: ThemeColors) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: c.background },
    content: { padding: 16, paddingBottom: 40 },
    centerContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: c.background,
    },
    loadingText: { marginTop: 12, fontSize: 16, color: c.textMuted },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 24,
      paddingTop: 8,
    },
    backButton: { padding: 8 },
    deleteHeaderButton: { padding: 8 },
    title: { fontSize: 20, fontWeight: 'bold', color: c.text },
    imagePicker: {
      height: 200,
      backgroundColor: c.surface,
      borderRadius: 16,
      marginBottom: 24,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: c.border,
      borderStyle: 'dashed',
    },
    imagePlaceholder: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    imageText: { marginTop: 8, color: c.textMuted, fontSize: 14 },
    image: { width: '100%', height: '100%' },
    formGroup: { marginBottom: 16 },
    row: { flexDirection: 'row' },
    label: { fontSize: 14, fontWeight: '500', color: c.textSecondary, marginBottom: 8 },
    input: {
      backgroundColor: c.inputBackground,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 12,
      padding: 16,
      fontSize: 16,
      color: c.text,
    },
    saveButton: {
      backgroundColor: c.primary,
      padding: 16,
      borderRadius: 12,
      alignItems: 'center',
      marginTop: 24,
    },
    saveButtonDisabled: { opacity: 0.7 },
    saveButtonText: { color: c.onPrimary, fontSize: 16, fontWeight: 'bold' },
    modalOverlay: { flex: 1, backgroundColor: c.overlay, justifyContent: 'flex-end' },
    modalContent: {
      backgroundColor: c.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      maxHeight: '70%',
      padding: 24,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    modalTitle: { fontSize: 18, fontWeight: 'bold', color: c.text },
    modalItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: c.borderLight,
    },
    modalItemText: { fontSize: 16, color: c.textSecondary },
    modalEmpty: { textAlign: 'center', color: c.textMuted, marginTop: 24 },
  });
}
