# Generated by Django 6.0.5 on 2026-07-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, help_text='Local ID from client', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
