"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

IS_VERCEL = os.environ.get('VERCEL') == '1'

_cloudinary_url = os.environ.get('CLOUDINARY_URL', '').strip()
_use_cloudinary = bool(_cloudinary_url) or all(
    os.environ.get(key, '').strip()
    for key in ('CLOUDINARY_CLOUD_NAME', 'CLOUDINARY_API_KEY', 'CLOUDINARY_API_SECRET')
)

if IS_VERCEL and not _use_cloudinary:
    raise ImproperlyConfigured(
        'CLOUDINARY_URL is required on Vercel for product images. '
        'Sign up at https://cloudinary.com and add CLOUDINARY_URL to your environment variables.'
    )

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-xbu&b3zx_5m1vbn%)r33wkabga2hn1s%znh)&*j41wuuz%h+ji',
)

# SECURITY WARNING: don't run with debug turned on in production!
_debug_default = 'False' if IS_VERCEL else 'True'
DEBUG = os.environ.get('DJANGO_DEBUG', _debug_default).lower() in ('true', '1', 'yes')

# Mobile / LAN testing: any host when DEBUG=True, or set DJANGO_ALLOWED_HOSTS=192.168.1.5,localhost
_allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '').strip()
if _allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',') if h.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['.vercel.app', 'localhost', '127.0.0.1']

_csrf_origins = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').strip()
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(',') if o.strip()]
elif not DEBUG:
    CSRF_TRUSTED_ORIGINS = ['https://*.vercel.app']

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    "tailwind",
    "theme",
    'api',
    'web',
]

if DEBUG:
    INSTALLED_APPS.append("django_browser_reload")

if _use_cloudinary:
    _static_idx = INSTALLED_APPS.index('django.contrib.staticfiles')
    INSTALLED_APPS[_static_idx:_static_idx] = ['cloudinary_storage', 'cloudinary']

TAILWIND_APP_NAME = "theme"

# Realtime dashboard (WebSockets) — install: pip install channels[daphne]
try:
    import channels  # noqa: F401
    import daphne  # noqa: F401

    CHANNELS_ENABLED = True
    INSTALLED_APPS.insert(0, 'daphne')
    INSTALLED_APPS.append('channels')
    ASGI_APPLICATION = 'project.asgi.application'
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
except ImportError:
    CHANNELS_ENABLED = False
    
NPM_BIN_PATH = "npm.cmd"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE.insert(3, "django_browser_reload.middleware.BrowserReloadMiddleware")

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_database_url = os.environ.get('DATABASE_URL', '').strip()
if _database_url:
    DATABASES = {
        'default': dj_database_url.config(
            default=_database_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif IS_VERCEL or not DEBUG:
    raise ImproperlyConfigured(
        'DATABASE_URL is required when deploying to Vercel or running with DEBUG=False. '
        'Use a hosted PostgreSQL database (Neon, Supabase, or Vercel Postgres).'
    )
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STORAGES = {
    'default': {
        'BACKEND': (
            'cloudinary_storage.storage.MediaCloudinaryStorage'
            if _use_cloudinary
            else 'django.core.files.storage.FileSystemStorage'
        ),
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

WHITENOISE_MANIFEST_STRICT = False

if _use_cloudinary and not _cloudinary_url:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ['CLOUDINARY_CLOUD_NAME'],
        'API_KEY': os.environ['CLOUDINARY_API_KEY'],
        'API_SECRET': os.environ['CLOUDINARY_API_SECRET'],
    }

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Receipt / store info (shown on printed receipts)
STORE_NAME = 'MyDream Inventory'
STORE_ADDRESS = ''
STORE_PHONE = ''

# Mobile app API URLs (QR code on dashboard)
# Local LAN uses http://<detected-ip>:MOBILE_API_PORT automatically.
# Set PUBLIC_API_URL when hosted online, e.g. https://inventory.yourdomain.com
PUBLIC_API_URL = os.environ.get('PUBLIC_API_URL', '').strip().rstrip('/')
MOBILE_API_PORT = int(os.environ.get('MOBILE_API_PORT', '8000'))
